import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'admin',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('admin123'),
      isAdmin: true,
    },
    {
      name: 'user1',
      email: 'user1@gmail.com',
      password: bcrypt.hashSync('user1234'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Iphone 14',
      slug: 'Iphone 14',
      category: 'Phone',
      image: '/images/phone/iphone14.jpg',
      price: 99800,
      brand: 'Apple',
      rating: 4.6,
      numReviews: 28,
      countInStock: 15,
      description: 'A magical new iPhone',
    },
    {
      name: 'Iphone 13',
      slug: 'Iphone 13',
      category: 'Phone',
      image: '/images/phone/iphone13.jpg',
      price: 86500,
      brand: 'Apple',
      rating: 4.8,
      numReviews: 18,
      countInStock: 25,
      description: 'A great iPhone',
    },
    {
      name: 'Iphone 12',
      slug: 'Iphone 12',
      category: 'Phone',
      image: '/images/phone/iphone12.jpg',
      price: 69000,
      brand: 'Apple',
      rating: 4.3,
      numReviews: 18,
      countInStock: 10,
      description: 'A stylish iPhone',
    },
    {
      name: 'Iphone 11',
      slug: 'Iphone 11',
      category: 'Phone',
      image: '/images/phone/iphone11.jpg',
      price: 55900,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 86,
      countInStock: 40,
      description: 'A stable iPhone',
    },
    {
      name: 'Samsung side by side refrigerator',
      slug: 'Samsung 101',
      category: 'refrigerator',
      image: '/images/refrigerator/samsung1.jpg',
      price: 175900,
      brand: 'Samsung',
      rating: 4.9,
      numReviews: 5,
      countInStock: 2,
      description: 'Huge family Refrigerator',
    },
    {
      name: 'Samsung three part refrigerator',
      slug: 'Samsung 102',
      category: 'refrigerator',
      image: '/images/refrigerator/samsung2.png',
      price: 14500,
      brand: 'Samsung',
      rating: 4.4,
      numReviews: 18,
      countInStock: 4,
      description: 'Multipurpose Refrigerator',
    },
    {
      name: 'Samsung super cool refrigerator',
      slug: 'Samsung 103',
      category: 'refrigerator',
      image: '/images/refrigerator/samsung3.jpg',
      price: 104999,
      brand: 'Samsung',
      rating: 4.9,
      numReviews: 27,
      countInStock: 5,
      description: 'Super chilled Refrigerator',
    },
    {
      name: 'Samsung designed refrigerator',
      slug: 'Samsung 104',
      category: 'refrigerator',
      image: '/images/refrigerator/samsung4.jpg',
      price: 65000,
      brand: 'Samsung',
      rating: 4.0,
      numReviews: 38,
      countInStock: 8,
      description: 'Beautiful Refrigerator',
    },
  ],
};

export default data;
